<a href="https://colab.research.google.com/github/jarminett/DCP/blob/main/Tarea06/Tarea6_Luis_Florian.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **UNIVERSIDAD GALILEO**
### Mestría en Data Science
#### Luis Florian, 0710072

### **Ejercicio 1**

#### **Diferencias entre np.array y np.matrix**
np.array y np.matrix ambos son utilizados para crear matrices.

**class numpy.matrix(data, dtype=None, copy=True)**

**numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)**

Los parámetros de cada uno varían, pero la idea general es la misma.  La principal diferencia es que matrix no es recomendado y en un futuro cercano desaparecerá.



In [ ]:
import numpy as np

In [ ]:
#Hay diferentes formas de crear matrices y eso puede variar entre array y matrx.
a = np.matrix('1 2; 3 4')
b = np.array('1 2; 3 4')
print("Matrix con matrix:",type(a))
print(a,"\n")
print("Matrix con array:",type(b))
print(b,"\n")


Matrix con matrix: <class 'numpy.matrix'>
[[1 2]
 [3 4]] 

Matrix con array: <class 'numpy.ndarray'>
1 2; 3 4 



In [ ]:
a = np.matrix([[1, 2], [3, 4]])
b = np.array([[1, 2], [3, 4]])
print("Matrix con matrix:",type(a))
print(a,"\n")
print("Matrix con array:",type(b))
print(b,"\n")

Matrix con matrix: <class 'numpy.matrix'>
[[1 2]
 [3 4]] 

Matrix con array: <class 'numpy.ndarray'>
[[1 2]
 [3 4]] 



In [ ]:
### **Ejercicio 1**

### **Ejercicio 2**
Implementar en una funcion neural_network(X) la red neuronal definida por la siguiente arquitectura:

<img src="http://i.imgur.com/UNlffE1.png">

In [52]:
def sigmoid(x): #convertir los valores de x al rango de 0 a 1    
    return 1/(1+np.exp(-x))

def relu(x):
    y = np.array(x)
    y[y<0] = 0    
    return x

def neural_network(X):
  H1_W = np.array([[0.712,0.355,0.268],
                 [0.112,0.855,0.468]])
  
  OL_W = np.array([0.116,0.329,0.708])

  H1 = np.dot(X,H1_W)
  H1 = sigmoid(H1)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1
  H1_Relu = relu(H1) 
  OL = np.dot(H1,OL_W)
  OL_Relu = np.dot(H1_Relu,OL_W)
  OL = sigmoid(OL)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1
  OL_Relu, relu(OL_Relu)
  return OL, OL_Relu

con_sigmoid, con_relu = neural_network([1,1])

print(f"Calculated (Con Sigmoid): {round(con_sigmoid,2)}")
print(f"Calculated (Con Relu): {round(con_relu,2)}")

Calculated (Con Sigmoid): 0.69
Calculated (Con Relu): 0.81


In [61]:
#Evalución
X = np.array([
    [0.1,2],
    [0.3,0.45],
    [5,9],
    [12,6],
    [7,5],
    [0.3,0.8],
    [12,5],
    [100,200],
    [7,8],
    [300,1500]])

con_sigmoid, con_relu = neural_network(X)

print(f"Calculated (Con Sigmoid)\n: {con_sigmoid}")
print(f"\nCalculated (Con Relu)\n: {con_relu}")

Calculated (Con Sigmoid)
: [0.70244573 0.66259284 0.75933678 0.75973948 0.75802295 0.6739704
 0.75954693 0.76005845 0.75952743 0.76005845]

Calculated (Con Relu)
: [0.85897151 0.6748703  1.14904686 1.15125178 1.14187076 0.72619803
 1.15019715 1.153      1.1500904  1.153     ]
